services:
  song-library:
    build: .
    container_name: song-library-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - EMLIB_DB_HOST=db
      - EMLIB_DB_PORT=5432
      - EMLIB_DB_USER=postgres
      - EMLIB_DB_PASSWORD=password
      - EMLIB_DB_NAME=em_library
      - EMLIB_SERVER_PORT=8080
      - EMLIB_SERVER_READ_TIMEOUT=1
      - EMLIB_SERVER_WRITE_TIMEOUT=2
      - EMLIB_SERVER_MODE=production
      - EMLIB_LOG_LEVEL=info
      - EMLIB_RUN_MIGRATIONS=1
      - EMLIB_INFOSERVICE_URL=http://host.docker.internal:8000
      - EMLIB_INFOSERVICE_TIMEOUT=500
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal

  db:
    image: postgres:17
    container_name: song-library-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=em_library
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d em_library'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

networks:
  internal:

volumes:
  postgres-data:
